import type { SeedOrganization } from './helpers';

/**
 * Organisations in the v1 corpus.
 *
 * Names, mandates, and web addresses are real public bodies and well-known
 * NGOs. Contact numbers and office hours are representative and carry
 * `verificationStatus: 'unverified_sample'` — the UI marks them accordingly.
 * Nothing here should be dialled or relied upon until a moderator verifies it.
 */
export const SEED_ORGANIZATIONS: readonly SeedOrganization[] = [
  {
    key: 'dss',
    name: ['Department of Social Services', 'সমাজসেবা অধিদফতর'],
    type: 'government',
    description: [
      'The Department of Social Services under the Ministry of Social Welfare administers Bangladesh\'s largest social safety-net allowances, including the old age, widow, and disability allowances.',
      'সমাজকল্যাণ মন্ত্রণালয়ের অধীন সমাজসেবা অধিদফতর বাংলাদেশের সবচেয়ে বড় সামাজিক নিরাপত্তা কর্মসূচিগুলো পরিচালনা করে — বয়স্ক ভাতা, বিধবা ভাতা ও প্রতিবন্ধী ভাতা এর মধ্যে অন্তর্ভুক্ত।',
    ],
    website: 'https://dss.gov.bd',
    contactPhone: '02-9349169',
    address: ['Samaj Seba Bhaban, Agargaon, Dhaka 1207', 'সমাজসেবা ভবন, আগারগাঁও, ঢাকা ১২০৭'],
    division: 'dhaka',
    district: 'dhaka',
    officeHours: ['Sunday–Thursday, 9:00 AM – 5:00 PM', 'রবি–বৃহস্পতি, সকাল ৯টা – বিকাল ৫টা'],
    verified: true,
  },
  {
    key: 'dwa',
    name: ['Department of Women Affairs', 'মহিলা বিষয়ক অধিদফতর'],
    type: 'government',
    description: [
      'Implements the Vulnerable Group Development (VGD) programme, maternity allowance, and women\'s skills training under the Ministry of Women and Children Affairs.',
      'মহিলা ও শিশু বিষয়ক মন্ত্রণালয়ের অধীনে ভিজিডি কর্মসূচি, মাতৃত্বকাল ভাতা এবং মহিলাদের দক্ষতা উন্নয়ন প্রশিক্ষণ পরিচালনা করে।',
    ],
    website: 'https://dwa.gov.bd',
    contactPhone: '02-9180753',
    address: ['37/3 Eskaton Garden Road, Dhaka 1000', '৩৭/৩ ইস্কাটন গার্ডেন রোড, ঢাকা ১০০০'],
    division: 'dhaka',
    district: 'dhaka',
    officeHours: ['Sunday–Thursday, 9:00 AM – 5:00 PM', 'রবি–বৃহস্পতি, সকাল ৯টা – বিকাল ৫টা'],
    verified: true,
  },
  {
    key: 'pmeat',
    name: ["Prime Minister's Education Assistance Trust", 'প্রধানমন্ত্রীর শিক্ষা সহায়তা ট্রাস্ট'],
    type: 'government',
    description: [
      'Provides stipends to financially disadvantaged but academically capable students from secondary through postgraduate level.',
      'আর্থিকভাবে অসচ্ছল কিন্তু মেধাবী শিক্ষার্থীদের মাধ্যমিক থেকে স্নাতকোত্তর পর্যায় পর্যন্ত উপবৃত্তি দেয়।',
    ],
    website: 'https://pmeat.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'shed',
    name: ['Ministry of Education (Secondary & Higher Education)', 'শিক্ষা মন্ত্রণালয় (মাধ্যমিক ও উচ্চশিক্ষা)'],
    type: 'government',
    description: [
      'Oversees secondary and higher education stipends, board scholarships, and the national scholarship framework.',
      'মাধ্যমিক ও উচ্চশিক্ষা স্তরের উপবৃত্তি, বোর্ড বৃত্তি এবং জাতীয় বৃত্তি কার্যক্রম দেখাশোনা করে।',
    ],
    website: 'https://shed.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'most',
    name: ['Ministry of Science and Technology', 'বিজ্ঞান ও প্রযুক্তি মন্ত্রণালয়'],
    type: 'government',
    description: [
      'Administers the National Science and Technology (NST) research fellowship and the Bangabandhu Science and Technology Fellowship.',
      'জাতীয় বিজ্ঞান ও প্রযুক্তি (এনএসটি) ফেলোশিপ এবং বঙ্গবন্ধু বিজ্ঞান ও প্রযুক্তি ফেলোশিপ পরিচালনা করে।',
    ],
    website: 'https://most.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'dae',
    name: ['Department of Agricultural Extension', 'কৃষি সম্প্রসারণ অধিদপ্তর'],
    type: 'government',
    description: [
      'Delivers agricultural input assistance, fertiliser subsidy distribution, crop rehabilitation support, and farmer training through upazila-level offices nationwide.',
      'সারা দেশে উপজেলা পর্যায়ের অফিসের মাধ্যমে কৃষি প্রণোদনা, সার ভর্তুকি বিতরণ, ফসল পুনর্বাসন সহায়তা ও কৃষক প্রশিক্ষণ দেয়।',
    ],
    website: 'https://dae.gov.bd',
    contactPhone: '16123',
    division: 'dhaka',
    district: 'dhaka',
    officeHours: ['Sunday–Thursday, 9:00 AM – 5:00 PM', 'রবি–বৃহস্পতি, সকাল ৯টা – বিকাল ৫টা'],
    verified: true,
  },
  {
    key: 'dls',
    name: ['Department of Livestock Services', 'প্রাণিসম্পদ অধিদপ্তর'],
    type: 'government',
    description: [
      'Provides livestock vaccination, veterinary services, poultry and dairy training, and rehabilitation support after disease outbreaks or disasters.',
      'গবাদি পশুর টিকা, পশুচিকিৎসা সেবা, হাঁস-মুরগি ও দুগ্ধ খামার প্রশিক্ষণ এবং রোগ বা দুর্যোগের পরে পুনর্বাসন সহায়তা দেয়।',
    ],
    website: 'https://dls.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'smef',
    name: ['SME Foundation', 'এসএমই ফাউন্ডেশন'],
    type: 'government',
    description: [
      'Apex body for small and medium enterprise development, offering credit wholesaling at concessional rates, business training, and market linkage support.',
      'ক্ষুদ্র ও মাঝারি উদ্যোগ উন্নয়নের শীর্ষ সংস্থা — রেয়াতি সুদে ঋণ, ব্যবসা প্রশিক্ষণ ও বাজার সংযোগ সহায়তা দেয়।',
    ],
    website: 'https://smef.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'bb',
    name: ['Bangladesh Bank', 'বাংলাদেশ ব্যাংক'],
    type: 'bank',
    description: [
      'The central bank operates refinance schemes for women entrepreneurs, agriculture, and cottage/micro/small enterprises, delivered through scheduled commercial banks.',
      'কেন্দ্রীয় ব্যাংক নারী উদ্যোক্তা, কৃষি এবং কুটির/মাইক্রো/ক্ষুদ্র উদ্যোগের জন্য পুনঃঅর্থায়ন তহবিল পরিচালনা করে, যা তফসিলি বাণিজ্যিক ব্যাংকের মাধ্যমে বিতরণ হয়।',
    ],
    website: 'https://bb.org.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'dyd',
    name: ['Department of Youth Development', 'যুব উন্নয়ন অধিদপ্তর'],
    type: 'government',
    description: [
      'Runs free vocational and self-employment training for young people, and issues youth loans to trained graduates.',
      'তরুণদের জন্য বিনামূল্যে কর্মমুখী ও আত্মকর্মসংস্থান প্রশিক্ষণ পরিচালনা করে এবং প্রশিক্ষিতদের যুব ঋণ দেয়।',
    ],
    website: 'https://dyd.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'bmet',
    name: ['Bureau of Manpower, Employment and Training', 'জনশক্তি, কর্মসংস্থান ও প্রশিক্ষণ ব্যুরো'],
    type: 'government',
    description: [
      'Regulates overseas employment, runs Technical Training Centres, and registers migrant workers for recruitment and pre-departure training.',
      'বিদেশে কর্মসংস্থান নিয়ন্ত্রণ করে, কারিগরি প্রশিক্ষণ কেন্দ্র পরিচালনা করে এবং প্রবাসী কর্মীদের নিবন্ধন ও প্রাক-বহির্গমন প্রশিক্ষণ দেয়।',
    ],
    website: 'https://bmet.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'nlaso',
    name: ['National Legal Aid Services Organisation', 'জাতীয় আইনগত সহায়তা প্রদান সংস্থা'],
    type: 'government',
    description: [
      'Provides free legal representation, mediation, and legal advice to citizens who cannot afford a lawyer, through district legal aid committees and the 16430 helpline.',
      'যারা আইনজীবীর খরচ বহন করতে পারেন না, তাদের জন্য জেলা লিগ্যাল এইড কমিটি ও ১৬৪৩০ হেল্পলাইনের মাধ্যমে বিনামূল্যে আইনি প্রতিনিধিত্ব, মধ্যস্থতা ও পরামর্শ দেয়।',
    ],
    website: 'https://nlaso.gov.bd',
    contactPhone: '16430',
    division: 'dhaka',
    district: 'dhaka',
    officeHours: ['Helpline 24/7; offices Sunday–Thursday', 'হেল্পলাইন ২৪/৭; অফিস রবি–বৃহস্পতি'],
    verified: true,
  },
  {
    key: 'dghs',
    name: ['Directorate General of Health Services', 'স্বাস্থ্য অধিদপ্তর'],
    type: 'government',
    description: [
      'Operates the public hospital network, community clinics, maternal health services, and the Shastho Batayon 16263 health helpline.',
      'সরকারি হাসপাতাল নেটওয়ার্ক, কমিউনিটি ক্লিনিক, মাতৃস্বাস্থ্য সেবা এবং স্বাস্থ্য বাতায়ন ১৬২৬৩ হেল্পলাইন পরিচালনা করে।',
    ],
    website: 'https://dghs.gov.bd',
    contactPhone: '16263',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'nicrh',
    name: ['National Institute of Cancer Research & Hospital', 'জাতীয় ক্যান্সার গবেষণা ইনস্টিটিউট ও হাসপাতাল'],
    type: 'hospital',
    description: [
      'The national referral centre for cancer treatment, providing subsidised chemotherapy, radiotherapy, and surgical oncology.',
      'ক্যান্সার চিকিৎসার জাতীয় রেফারেল কেন্দ্র — ভর্তুকি মূল্যে কেমোথেরাপি, রেডিওথেরাপি ও অনকোলজি সার্জারি সেবা দেয়।',
    ],
    website: 'https://nicrh.gov.bd',
    address: ['Mohakhali, Dhaka 1212', 'মহাখালী, ঢাকা ১২১২'],
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'nimh',
    name: ['National Institute of Mental Health', 'জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউট'],
    type: 'hospital',
    description: [
      'Specialised public mental health hospital offering outpatient counselling, psychiatric treatment, and inpatient care.',
      'বিশেষায়িত সরকারি মানসিক স্বাস্থ্য হাসপাতাল — বহির্বিভাগে কাউন্সেলিং, মানসিক রোগের চিকিৎসা ও আন্তঃবিভাগ সেবা দেয়।',
    ],
    website: 'https://nimh.gov.bd',
    address: ['Sher-e-Bangla Nagar, Dhaka 1207', 'শেরেবাংলা নগর, ঢাকা ১২০৭'],
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'brac',
    name: ['BRAC', 'ব্র্যাক'],
    type: 'ngo',
    description: [
      'The world\'s largest non-governmental development organisation, running ultra-poor graduation, education, microfinance, health, and legal empowerment programmes across Bangladesh.',
      'বিশ্বের বৃহত্তম বেসরকারি উন্নয়ন সংস্থা — বাংলাদেশ জুড়ে অতিদরিদ্র উন্নয়ন, শিক্ষা, ক্ষুদ্রঋণ, স্বাস্থ্য ও আইনি ক্ষমতায়ন কর্মসূচি পরিচালনা করে।',
    ],
    website: 'https://brac.net',
    contactPhone: '16445',
    address: ['BRAC Centre, 75 Mohakhali, Dhaka 1212', 'ব্র্যাক সেন্টার, ৭৫ মহাখালী, ঢাকা ১২১২'],
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'blast',
    name: ['Bangladesh Legal Aid and Services Trust', 'বাংলাদেশ লিগ্যাল এইড অ্যান্ড সার্ভিসেস ট্রাস্ট'],
    type: 'ngo',
    description: [
      'Provides free legal aid, litigation support, and mediation to marginalised citizens, with a focus on women, workers, and detainees.',
      'প্রান্তিক নাগরিকদের — বিশেষত নারী, শ্রমিক ও আটক ব্যক্তিদের — বিনামূল্যে আইনি সহায়তা, মামলা পরিচালনা ও মধ্যস্থতা সেবা দেয়।',
    ],
    website: 'https://blast.org.bd',
    address: ['1/1 Pioneer Road, Kakrail, Dhaka 1000', '১/১ পাইওনিয়ার রোড, কাকরাইল, ঢাকা ১০০০'],
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'pksf',
    name: ['Palli Karma-Sahayak Foundation', 'পল্লী কর্ম-সহায়ক ফাউন্ডেশন'],
    type: 'government',
    description: [
      'Apex financing body channelling concessional microcredit and enterprise finance to the rural poor through partner organisations.',
      'অংশীদার সংস্থার মাধ্যমে গ্রামীণ দরিদ্রদের কাছে রেয়াতি ক্ষুদ্রঋণ ও উদ্যোগ অর্থায়ন পৌঁছে দেওয়া শীর্ষ অর্থায়ন সংস্থা।',
    ],
    website: 'https://pksf.org.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'ddm',
    name: ['Department of Disaster Management', 'দুর্যোগ ব্যবস্থাপনা অধিদপ্তর'],
    type: 'government',
    description: [
      'Coordinates cyclone and flood preparedness, gratuitous relief, house reconstruction grants, and post-disaster rehabilitation.',
      'ঘূর্ণিঝড় ও বন্যা প্রস্তুতি, ত্রাণ, ঘর পুনর্নির্মাণ অনুদান এবং দুর্যোগ-পরবর্তী পুনর্বাসন সমন্বয় করে।',
    ],
    website: 'https://ddm.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'ugc',
    name: ['University Grants Commission of Bangladesh', 'বাংলাদেশ বিশ্ববিদ্যালয় মঞ্জুরি কমিশন'],
    type: 'university',
    description: [
      'Regulates higher education and administers research grants and fellowships for university faculty and postgraduate researchers.',
      'উচ্চশিক্ষা নিয়ন্ত্রণ করে এবং বিশ্ববিদ্যালয় শিক্ষক ও স্নাতকোত্তর গবেষকদের জন্য গবেষণা অনুদান ও ফেলোশিপ পরিচালনা করে।',
    ],
    website: 'https://ugc.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'nsda',
    name: ['National Skills Development Authority', 'জাতীয় দক্ষতা উন্নয়ন কর্তৃপক্ষ'],
    type: 'training_center',
    description: [
      'Coordinates national vocational skills training and certification, including free courses for unemployed youth and returning migrants.',
      'জাতীয় কর্মমুখী দক্ষতা প্রশিক্ষণ ও সনদায়ন সমন্বয় করে — বেকার তরুণ ও প্রত্যাগত প্রবাসীদের জন্য বিনামূল্যে কোর্স অন্তর্ভুক্ত।',
    ],
    website: 'https://nsda.gov.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'kidney_foundation',
    name: ['Kidney Foundation Bangladesh', 'কিডনি ফাউন্ডেশন বাংলাদেশ'],
    type: 'ngo',
    description: [
      'Charitable hospital providing subsidised and free dialysis, transplant support, and kidney disease screening for low-income patients.',
      'দানশীল হাসপাতাল — নিম্ন আয়ের রোগীদের জন্য ভর্তুকি ও বিনামূল্যে ডায়ালাইসিস, প্রতিস্থাপন সহায়তা ও কিডনি রোগ পরীক্ষা দেয়।',
    ],
    website: 'https://kidneyfoundationbd.com',
    address: ['Plot 5/2, Road 1, Section 2, Mirpur, Dhaka 1216', 'প্লট ৫/২, রোড ১, সেকশন ২, মিরপুর, ঢাকা ১২১৬'],
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'ahsania',
    name: ['Dhaka Ahsania Mission', 'ঢাকা আহ্‌ছানিয়া মিশন'],
    type: 'ngo',
    description: [
      'NGO working in non-formal education, adult literacy, cancer care, and drug rehabilitation across Bangladesh.',
      'উপানুষ্ঠানিক শিক্ষা, বয়স্ক শিক্ষা, ক্যান্সার সেবা ও মাদকাসক্তি পুনর্বাসন নিয়ে সারা দেশে কাজ করা একটি এনজিও।',
    ],
    website: 'https://ahsaniamission.org.bd',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
  {
    key: 'jms',
    name: ['Jatiyo Mohila Sangstha', 'জাতীয় মহিলা সংস্থা'],
    type: 'government',
    description: [
      'National women\'s organisation delivering skills training, legal counselling, and the 109 helpline for violence against women.',
      'জাতীয় মহিলা সংস্থা — দক্ষতা প্রশিক্ষণ, আইনি পরামর্শ এবং নারী নির্যাতন প্রতিরোধে ১০৯ হেল্পলাইন পরিচালনা করে।',
    ],
    website: 'https://jms.gov.bd',
    contactPhone: '109',
    division: 'dhaka',
    district: 'dhaka',
    verified: true,
  },
];
